services:
  scheduler:
    volumes:
      - type: bind
        source: ${USERPROFILE}/.kaggle/kaggle.json
        target: /home/astro/.kaggle/kaggle.json
        read_only: true
  api-server:
    volumes:
      - type: bind
        source: ${USERPROFILE}/.kaggle/kaggle.json
        target: /home/astro/.kaggle/kaggle.json
        read_only: true
  dag-processor:
    volumes:
      - type: bind
        source: ${USERPROFILE}/.kaggle/kaggle.json
        target: /home/astro/.kaggle/kaggle.json
        read_only: true