version: "3.1"
services:
  scheduler:
    volumes:
      - ${USERPROFILE}/.kaggle/kaggle.json:/home/astro/.kaggle/kaggle.json:ro
  webserver:
    volumes:
      - ${USERPROFILE}/.kaggle/kaggle.json:/home/astro/.kaggle/kaggle.json:ro